
------------------------------ERROR------------------------------
14/02/2022 21:19:23 - UnableToWorkException: I知 not hired yet, lol
Traceback (most recent call last):
  File "F:\IT\MyScripts\oop\app.py", line 25, in <module>
    main()
  File "F:\IT\MyScripts\oop\app.py", line 20, in main
    cand3.work()
  File "F:\IT\MyScripts\oop\models.py", line 162, in __getattr__
    raise UnableToWorkException('I知 not hired yet, lol')
models.UnableToWorkException: I知 not hired yet, lol

------------------------------ERROR------------------------------
14/02/2022 21:19:30 - UnableToWorkException: I知 not hired yet, lol
Traceback (most recent call last):
  File "F:\IT\MyScripts\oop\app.py", line 25, in <module>
    main()
  File "F:\IT\MyScripts\oop\app.py", line 20, in main
    cand3.work()
  File "F:\IT\MyScripts\oop\models.py", line 162, in __getattr__
    raise UnableToWorkException('I知 not hired yet, lol')
models.UnableToWorkException: I知 not hired yet, lol

------------------------------ERROR------------------------------
14/02/2022 21:19:59 - UnableToWorkException: I知 not hired yet, lol
Traceback (most recent call last):
  File "F:\IT\MyScripts\oop\app.py", line 25, in <module>
    main()
  File "F:\IT\MyScripts\oop\app.py", line 20, in main
    cand3.work()
  File "F:\IT\MyScripts\oop\models.py", line 162, in __getattr__
    raise UnableToWorkException('I知 not hired yet, lol')
models.UnableToWorkException: I知 not hired yet, lol

------------------------------ERROR------------------------------
14/02/2022 21:20:04 - UnableToWorkException: I知 not hired yet, lol
Traceback (most recent call last):
  File "F:\IT\MyScripts\oop\app.py", line 25, in <module>
    main()
  File "F:\IT\MyScripts\oop\app.py", line 20, in main
    cand3.work()
  File "F:\IT\MyScripts\oop\models.py", line 162, in __getattr__
    raise UnableToWorkException('I知 not hired yet, lol')
models.UnableToWorkException: I知 not hired yet, lol
